# -*- coding: utf-8 -*-
"""Lista.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBzO0JztO_5TC5JH-wP9xB-uFzuggyqs
"""

#1 Ler uma lista de 5 numeros inteiros e mostre cada numero juntamente com a sua posição na lista
lista_2=[2,5,6,9]
for i, item in enumerate(lista_2): #enumerate: considera como se fosse numerar os itens
  print(f'{i}:{item}')

#2 Ler uma lista de 10 numeros reais e mostre-os na ordem inversa que foram lidos
lista_inv=[1,2,3,5,8,-5,-3,7,10,4]
lista_inv.reverse()
print(lista_inv)

#3 Ler uma lista com 5 idades e exibir a maior e a menor
idade= [10,21,33,7,12]
print(min(idade),max(idade))

#4 Inicalize uma lista de 10 numeros interios. Armazene os números pares em uma lista PAR e os números impares em uma lista IMPAR. Imprema as listas PAR e IMPAR

lista_10=[1,5,7,6,8,9,10,20,18,32]
apenas_pares=[x for x in lista_10 if x % 2 == 0]
apenas_impares=[x for x in lista_10 if x % 2 != 0]
print(apenas_pares)
print(apenas_impares)

#5 Escreva um programa que troque o primeiro com o último elemento de uma lista qualquer.
lista=['joao','pedro','maria','beatriz']
lista.insert(0,lista[-1])
lista.pop()
lista.append(lista[1])
lista.pop(1)
print(lista)

#6 Qual a saída/resultado da seguinte compreensão de lista?
 [[1 + j*3+i for i in range(3)]for j in range(3)]
 #a saída da lista representa uma matriz 3x3, no qual foi aplicada através da utilização do for dentro de outro for

#7 Considere que você recebe um dicionário contendo informações sobre produtos em uma loja. Cada chave do dicionário é o nome de um produto e cada valor é uma tupla  contendo o preço e a quantidade em estoque desse produto.
produtos = {
  'camiseta': (25.00, 10),
  'calça': (45.00, 5),
  'sapato': (60.00, 3),
  'boné': (15.00, 8)
}
preço= input("Digite um valor para checar os produtos com valor menor ou igual ao preço digitado: ")
if not preço.strip().isnumeric():
  print("Digite um preço válido!")
else:
  for produto, valor in produtos.items():
    if valor[0] <= float(preço):
      print(produto, valor)

#

#8. Em uma competição de ginástica, cada atleta recebe votos de sete jurados. A melhor e a pior nota são eliminadas.
#A sua nota fica  sendo a média dos votos restantes. Você deve fazer um programa que receba o nome do ginasta e as notas dos sete jurados alcançadas pelo atleta em sua apresentação e depois informe a sua média, conforme a descrição acima informada (retirar o melhor e o pior salto e depois calcular a média com as notas restantes). As notas não são informadas em ordem crescente ou decrescente


nome= input("Digite o nome do ginasta: ")
notas= []
cont = 0
n_jurados= 7
while cont < n_jurados:
  nota = float(input(f'nota{cont+1}:'))
  notas.append(nota)
  cont += 1
  print(notas)
  notas.sort()
  print(notas)
  notas_finais = notas [1:-1]
  print(notas_finais)
  media = sum(notas_finais)/len(notas_finais)
  print(f'Ginasta{nome}:nota{media}')